import type { Car } from "./definitions";

export const cars: Car[] = [
  {
    id: "1",
    brand: "Tesla",
    model: "Model 3",
    variant: "Long Range",
    condition: "Ocasión",
    price: 45990,
    financePrice: Math.round(45990 * 0.96),
    monthlyPrice: 599,
    fuel: "Eléctrico",
    year: 2023,
    mileage: 12000,
    bodyType: "Berlina",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 350,
    color: "Blanco",
    doors: 5,
    electricRange: 580,
    batteryCapacity: 75,
    chargingTime: 8,
    fastCharge: true,
    chargingPort: "CCS",
    images: ["/coches/tesla-model-3.jpg"],
    ivaDeductible: true,
    location: "Sevilla",
    features: [
      "Autopilot",
      "Carga rápida",
      "Pantalla táctil",
      "Asientos calefactables",
    ],
    description:
      "Tesla Model 3 Long Range con autonomía de 580 km y equipamiento premium.",
  },
  {
    id: "2",
    brand: "BMW",
    model: "i4",
    variant: "eDrive40",
    condition: "Km 0",
    price: 59900,
    financePrice: Math.round(59900 * 0.96),
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2023,
    mileage: 1500,
    bodyType: "Berlina",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "Trasera",
    power: 340,
    color: "Azul",
    doors: 4,
    electricRange: 590,
    batteryCapacity: 83.9,
    chargingTime: 8.5,
    fastCharge: true,
    chargingPort: "CCS",
    images: ["/coches/bmw-i4.jpg"],
    ivaDeductible: true,
    location: "Sevilla",
    features: [
      "BMW iDrive",
      "Asistente de conducción",
      "Sonido Harman Kardon",
      "Techo panorámico",
    ],
    description:
      "BMW i4 eDrive40 con autonomía de 590 km y equipamiento completo.",
  },
  {
    id: "3",
    brand: "Audi",
    model: "e-tron GT",
    variant: "quattro",
    condition: "Seminuevo",
    price: 104900,
    financePrice: Math.round(104900 * 0.96),
    monthlyPrice: 1299,
    fuel: "Eléctrico",
    year: 2022,
    mileage: 15000,
    bodyType: "Berlina",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 476,
    color: "Gris",
    doors: 4,
    electricRange: 488,
    batteryCapacity: 93.4,
    chargingTime: 9,
    fastCharge: true,
    chargingPort: "CCS",
    images: ["/coches/audi-etron-gt.jpg"],
    ivaDeductible: false,
    location: "Sevilla",
    features: [
      "Tracción quattro",
      "Carga rápida 270kW",
      "Sonido Bang & Olufsen",
      "Asientos deportivos",
    ],
    description:
      "Audi e-tron GT quattro con autonomía de 488 km y equipamiento completo.",
  },
  {
    id: "4",
    brand: "Porsche",
    model: "Taycan",
    variant: "Turbo S",
    condition: "Ocasión",
    price: 189900,
    financePrice: Math.round(189900 * 0.96),
    monthlyPrice: 2199,
    fuel: "Eléctrico",
    year: 2023,
    mileage: 0,
    bodyType: "Berlina",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 761,
    color: "Rojo",
    doors: 4,
    electricRange: 412,
    batteryCapacity: 93.4,
    chargingTime: 9,
    fastCharge: true,
    chargingPort: "CCS",
    images: ["/coches/porsche-taycan.jpg"],
    ivaDeductible: false,
    location: "Sevilla",
    features: [
      "Porsche Electric Sport Sound",
      "Carga rápida 270kW",
      "Suspensión neumática adaptativa",
      "Porsche Dynamic Chassis Control",
    ],
    description:
      "Porsche Taycan Turbo S con autonomía de 412 km y equipamiento completo.",
  },
  {
    id: "5",
    brand: "Audi",
    model: "A4",
    variant: "2.0 TDI",
    condition: "Segunda mano",
    price: 18900,
    financePrice: Math.round(18900 * 0.96),
    monthlyPrice: 299,
    fuel: "Diésel",
    year: 2014,
    mileage: 120000,
    bodyType: "Berlina",
    transmission: "Manual",
    environmentalTag: "C",
    drivetrain: "Delantera",
    power: 150,
    engineDisplacement: 1968,
    color: "Gris Plata",
    doors: 4,
    images: ["/coches/audi-a4.jpg"],
    ivaDeductible: false,
    location: "Sevilla",
    features: [
      "Navegador MMI",
      "Faros Xenón",
      "Sensores de aparcamiento",
      "Volante multifunción",
    ],
    description:
      "Audi A4 2.0 TDI de 150 CV en excelente estado.",
  },
  {
    id: "6",
    brand: "Toyota",
    model: "Tacoma",
    variant: "TRD Sport 4x4",
    condition: "Seminuevo",
    price: 34900,
    financePrice: Math.round(34900 * 0.96),
    monthlyPrice: 499,
    fuel: "Gasolina",
    year: 2019,
    mileage: 45000,
    bodyType: "Pickup",
    transmission: "Automático",
    environmentalTag: "C",
    drivetrain: "4x4",
    power: 278,
    engineDisplacement: 3500,
    color: "Gris Cemento",
    doors: 4,
    images: ["/coches/toyota-tacoma.webp"],
    ivaDeductible: false,
    location: "Sevilla",
    features: [
      "Tracción 4x4",
      'Pantalla táctil 8"',
      "Asientos calefactados",
      "Control de descenso",
    ],
    description:
      "Toyota Tacoma TRD Sport 4x4 con motor V6 y pantalla táctil de 8 pulgadas.",
  },
  {
    id: "7",
    brand: "Porsche",
    model: "911",
    variant: "Carrera S",
    condition: "Segunda mano",
    price: 59900,
    financePrice: Math.round(59900 * 0.96),
    monthlyPrice: 749,
    fuel: "Gasolina",
    year: 2009,
    mileage: 90000,
    bodyType: "Coupé",
    transmission: "Automático",
    environmentalTag: "C",
    drivetrain: "Trasera",
    power: 385,
    engineDisplacement: 3800,
    color: "Rojo",
    doors: 2,
    images: ["/coches/porsche-911.jpg"],
    ivaDeductible: false,
    location: "Sevilla",
    features: [
      "Sistema PCM",
      "Asientos deportivos",
      "Frenos cerámicos PCCB",
      "Suspensión PASM",
    ],
    description:
      "Porsche 911 Carrera S de 2009 con motor bóxer de 385 CV.",
  },
  {
    id: "8",
    brand: "Hyundai",
    model: "IONIQ 5",
    variant: "73 kWh AWD",
    condition: "Ocasión",
    price: 52900,
    financePrice: Math.round(52900 * 0.96),
    monthlyPrice: 649,
    fuel: "Eléctrico",
    year: 2023,
    mileage: 0,
    bodyType: "SUV",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 305,
    color: "Gris",
    doors: 5,
    electricRange: 480,
    batteryCapacity: 77.4,
    chargingTime: 7.5,
    fastCharge: true,
    chargingPort: "CCS",
    images: [],
    ivaDeductible: true,
    location: "Sevilla",
    features: [
      "Carga ultrarrápida 350kW",
      "Vehicle-to-Load",
      "Head-up display",
    ],
    description:
      "Hyundai IONIQ 5 73 kWh AWD con autonomía de 480 km.",
  },
  {
    id: "9",
    brand: "Kia",
    model: "EV6",
    variant: "GT-Line AWD",
    condition: "Km 0",
    price: 59900,
    financePrice: Math.round(59900 * 0.96),
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2023,
    mileage: 1000,
    bodyType: "SUV",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 325,
    color: "Negro",
    doors: 5,
    electricRange: 506,
    batteryCapacity: 77.4,
    chargingTime: 7,
    fastCharge: true,
    chargingPort: "CCS",
    images: [],
    ivaDeductible: true,
    location: "Sevilla",
    features: [
      "Carga ultrarrápida 350kW",
      "Vehicle-to-Load",
      "Meridian Premium Sound",
      "Asistente de conducción",
    ],
    description:
      "Kia EV6 GT-Line AWD con autonomía de 506 km y equipamiento completo.",
  },
  {
    id: "10",
    brand: "Polestar",
    model: "2",
    variant: "Long Range Dual Motor",
    condition: "Seminuevo",
    price: 58900,
    financePrice: Math.round(58900 * 0.96),
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2022,
    mileage: 25000,
    bodyType: "SUV",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 408,
    color: "Blanco",
    doors: 5,
    electricRange: 480,
    batteryCapacity: 75,
    chargingTime: 8,
    fastCharge: true,
    chargingPort: "CCS",
    images: [],
    ivaDeductible: false,
    location: "Sevilla",
    features: [
      "Google built-in",
      "Carga rápida 150kW",
      "Harman Kardon Premium Sound",
      "Pilot Assist",
    ],
    description:
      "Polestar 2 Long Range Dual Motor con autonomía de 480 km y equipamiento completo.",
  },
  {
    id: "11",
    brand: "Jaguar",
    model: "I-PACE",
    variant: "EV400 HSE",
    condition: "Seminuevo",
    price: 79900,
    financePrice: Math.round(79900 * 0.96),
    monthlyPrice: 899,
    fuel: "Eléctrico",
    year: 2022,
    mileage: 30000,
    bodyType: "SUV",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 400,
    color: "Gris",
    doors: 5,
    electricRange: 470,
    batteryCapacity: 90,
    chargingTime: 10,
    fastCharge: true,
    chargingPort: "CCS",
    images: [],
    ivaDeductible: true,
    location: "Sevilla",
    features: [
      "Pivi Pro",
      "Carga rápida 100kW",
      "Meridian 3D Surround Sound",
      "Asientos deportivos",
    ],
    description:
      "Jaguar I-PACE EV400 HSE con autonomía de 470 km y equipamiento completo.",
  },
  {
    id: "12",
    brand: "Volvo",
    model: "C40",
    variant: "Recharge Twin",
    condition: "Ocasión",
    price: 57900,
    financePrice: Math.round(57900 * 0.96),
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2023,
    mileage: 0,
    bodyType: "SUV",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 408,
    color: "Azul",
    doors: 5,
    electricRange: 451,
    batteryCapacity: 78,
    chargingTime: 8,
    fastCharge: true,
    chargingPort: "CCS",
    images: [],
    ivaDeductible: true,
    location: "Sevilla",
    features: [
      "Google built-in",
      "Carga rápida 150kW",
      "Harman Kardon Premium Sound",
      "Pilot Assist",
    ],
    description:
      "Volvo C40 Recharge Twin con autonomía de 451 km y equipamiento completo.",
  },
  {
    id: "13",
    brand: "Volvo",
    model: "C50",
    variant: "Recharge Twin",
    condition: "Ocasión",
    price: 57900,
    financePrice: Math.round(57900 * 0.96),
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2023,
    mileage: 0,
    bodyType: "SUV",
    transmission: "Automático",
    environmentalTag: "CERO",
    drivetrain: "4x4",
    power: 408,
    color: "Azul",
    doors: 5,
    electricRange: 451,
    batteryCapacity: 78,
    chargingTime: 8,
    fastCharge: true,
    chargingPort: "CCS",
    images: [],
    ivaDeductible: true,
    location: "Sevilla",
    features: [
      "Google built-in",
      "Carga rápida 150kW",
      "Harman Kardon Premium Sound",
      "Pilot Assist",
    ],
    description:
      "Volvo C50 Recharge Twin con autonomía de 451 km y equipamiento completo.",
  },
];
